// Utility functions for exporting proposals

export interface ProposalData {
  title: string;
  content: string;
  date?: string;
}

export interface ShareLinkData {
  id: string;
  proposal: ProposalData;
  sharedAt: string;
}

/**
 * Copy text to clipboard with fallback for older browsers
 * @param text - Text to copy
 * @returns Promise<boolean> - Success status
 */
export const copyToClipboard = async (text: string): Promise<boolean> => {
  try {
    // Modern browsers with clipboard API
    if (navigator.clipboard && window.isSecureContext) {
      await navigator.clipboard.writeText(text);
      return true;
    }
    
    // Fallback for older browsers
    const textArea = document.createElement('textarea');
    textArea.value = text;
    textArea.style.position = 'fixed';
    textArea.style.left = '-999999px';
    textArea.style.top = '-999999px';
    document.body.appendChild(textArea);
    textArea.focus();
    textArea.select();
    
    const successful = document.execCommand('copy');
    document.body.removeChild(textArea);
    
    return successful;
  } catch (error) {
    console.error('Failed to copy text:', error);
    throw new Error('Failed to copy text to clipboard');
  }
};

/**
 * Download content as a text file
 * @param content - Text content to download
 * @param filename - Name of the file (without extension)
 * @returns void
 */
export const downloadAsTxt = (content: string, filename: string = 'proposal'): void => {
  try {
    // Create blob with UTF-8 encoding
    const blob = new Blob([content], { type: 'text/plain;charset=utf-8' });
    
    // Create download link
    const url = URL.createObjectURL(blob);
    const link = document.createElement('a');
    link.href = url;
    link.download = `${filename}.txt`;
    
    // Trigger download
    document.body.appendChild(link);
    link.click();
    document.body.removeChild(link);
    
    // Clean up URL
    URL.revokeObjectURL(url);
  } catch (error) {
    console.error('Failed to download as TXT:', error);
    throw new Error('Failed to download proposal as text file');
  }
};

/**
 * Generate formatted content for PDF export
 * @param proposal - Proposal object with title and content
 * @returns string - Formatted HTML content
 */
export const generatePdfContent = (proposal: ProposalData): string => {
  const currentDate = new Date().toLocaleDateString();
  
  return `
    <!DOCTYPE html>
    <html>
    <head>
      <meta charset="utf-8">
      <title>${proposal.title}</title>
      <style>
        body {
          font-family: 'Inter', -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
          line-height: 1.6;
          color: #1f2937;
          max-width: 800px;
          margin: 0 auto;
          padding: 40px 20px;
          background: white;
        }
        .header {
          text-align: center;
          margin-bottom: 40px;
          border-bottom: 2px solid #e5e7eb;
          padding-bottom: 20px;
        }
        .title {
          font-size: 28px;
          font-weight: bold;
          color: #111827;
          margin: 0 0 10px 0;
        }
        .date {
          color: #6b7280;
          font-size: 14px;
          margin: 0;
        }
        .content {
          white-space: pre-wrap;
          font-size: 16px;
          line-height: 1.8;
          color: #374151;
        }
        .footer {
          margin-top: 40px;
          padding-top: 20px;
          border-top: 1px solid #e5e7eb;
          text-align: center;
          color: #9ca3af;
          font-size: 12px;
        }
        @media print {
          body { margin: 0; padding: 20px; }
          .header { margin-bottom: 30px; }
          .title { font-size: 24px; }
          .content { font-size: 14px; }
        }
      </style>
    </head>
    <body>
      <div class="header">
        <h1 class="title">${proposal.title}</h1>
        <p class="date">Generated on ${currentDate}</p>
      </div>
      <div class="content">${proposal.content}</div>
      <div class="footer">
        <p>Generated by ProposalGen AI</p>
      </div>
    </body>
    </html>
  `;
};

/**
 * Export content as PDF using browser print functionality
 * @param proposal - Proposal object with title and content
 * @returns Promise<void>
 */
export const exportAsPdf = async (proposal: ProposalData): Promise<void> => {
  try {
    // Generate HTML content
    const htmlContent = generatePdfContent(proposal);
    
    // Create a new window for printing
    const printWindow = window.open('', '_blank');
    
    if (!printWindow) {
      throw new Error('Failed to open print window. Please allow popups and try again.');
    }
    
    // Write content to the new window
    printWindow.document.write(htmlContent);
    printWindow.document.close();
    
    // Wait for content to load, then trigger print
    printWindow.onload = () => {
      setTimeout(() => {
        printWindow.print();
        
        // Close the window after printing (or after user cancels)
        printWindow.onafterprint = () => {
          printWindow.close();
        };
        
        // Fallback timeout to close window
        setTimeout(() => {
          if (!printWindow.closed) {
            printWindow.close();
          }
        }, 1000);
      }, 500);
    };
    
  } catch (error) {
    console.error('Failed to export as PDF:', error);
    throw new Error('Failed to export proposal as PDF');
  }
};

/**
 * Alternative PDF export using html2canvas and jsPDF (if libraries are available)
 * @param proposal - Proposal object with title and content
 * @returns Promise<void>
 */
export const exportAsPdfAdvanced = async (proposal: ProposalData): Promise<void> => {
  try {
    // Check if required libraries are available (they would be loaded dynamically if needed)
    const html2canvas = (window as any).html2canvas;
    const jspdf = (window as any).jspdf;
    
    if (!html2canvas || !jspdf) {
      // Fallback to print method
      return await exportAsPdf(proposal);
    }
    
    // Create a temporary div with the content
    const tempDiv = document.createElement('div');
    tempDiv.innerHTML = generatePdfContent(proposal);
    tempDiv.style.position = 'absolute';
    tempDiv.style.left = '-9999px';
    tempDiv.style.width = '800px';
    document.body.appendChild(tempDiv);
    
    // Convert to canvas
    const canvas = await html2canvas(tempDiv, {
      scale: 2,
      useCORS: true,
      allowTaint: true
    });
    
    // Create PDF
    const pdf = new jspdf.jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'a4'
    });
    
    const imgData = canvas.toDataURL('image/png');
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    
    pdf.addImage(imgData, 'PNG', 0, 0, pdfWidth, pdfHeight);
    pdf.save(`${proposal.title.replace(/\s+/g, '_').toLowerCase()}.pdf`);
    
    // Clean up
    document.body.removeChild(tempDiv);
    
  } catch (error) {
    console.error('Failed to export as PDF (advanced):', error);
    // Fallback to print method
    return await exportAsPdf(proposal);
  }
};

/**
 * Generate a shareable link for the proposal
 * @param proposal - Proposal object
 * @returns string - Shareable URL
 */
export const generateShareLink = (proposal: ProposalData): string => {
  const baseUrl = window.location.origin;
  const proposalId = Date.now().toString(36);
  const shareUrl = `${baseUrl}/proposal/${proposalId}`;
  
  // Store proposal in localStorage for sharing (in production, this would be a database)
  const sharedProposals: Record<string, ShareLinkData> = JSON.parse(localStorage.getItem('sharedProposals') || '{}');
  sharedProposals[proposalId] = {
    id: proposalId,
    proposal: proposal,
    sharedAt: new Date().toISOString()
  };
  localStorage.setItem('sharedProposals', JSON.stringify(sharedProposals));
  
  return shareUrl;
};

/**
 * Validate proposal content before export
 * @param proposal - Proposal object to validate
 * @returns boolean - Validation result
 */
export const validateProposal = (proposal: ProposalData): boolean => {
  if (!proposal) return false;
  if (!proposal.title || typeof proposal.title !== 'string') return false;
  if (!proposal.content || typeof proposal.content !== 'string') return false;
  if (proposal.content.trim().length === 0) return false;
  
  return true;
};
